---
title: "Bayesian_Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Libraries*
```{r}
library(tidyverse)
library(ggExtra)
library(ggplot2)
source('TeachBayes.r')
```

```{r}
#Load data from Github
math_student_data_url <- "https://raw.githubusercontent.com/arunk13/MSDA-Assignments/master/IS607Fall2015/Assignment3/student-mat.csv";
math_student_data <- read.table(file = math_student_data_url, header = TRUE, sep = ";");
eng_student_data_url <- "https://raw.githubusercontent.com/arunk13/MSDA-Assignments/master/IS607Fall2015/Assignment3/student-por.csv";
eng_student_data <- read.table(file = eng_student_data_url, header = TRUE, sep = ";")
studentdata <- rbind(math_student_data, eng_student_data)


#Clean Data
studentdata[c("G1","G2","G3")] <- studentdata[c("G1","G2","G3")] * 5
#Grades were originally out of 20 (Based on european grading scale) but for Ireland we would like our results out of 100.
```

*Defining prior*
```{r}
m0 <- 60
s0 <- 1 #Sigma_0 (Using a larger value for sigma_0 to allow for extra variation in Final Grade)

myplot <- ggplot(studentdata, aes(x=age,y=G3)) + geom_point() + 
  geom_abline(intercept=0,slope=1) 
ggMarginal(myplot, type = "histogram")
```

*Likelihood*
```{r}
xbar <- mean(studentdata$G3)
sigma <- 15
n = length(studentdata$G3)
se <- sigma/sqrt(n)
```
*Plot the prior, data and posterior*
```{r}
Prior <- c(m0, s0)
Data <- c(xbar, se)
Posterior <- round(normal_update(Prior, Data),3)
x <- seq(0, 100, length=1000)
priorx <- dnorm(x, mean=m0,   sd=s0)
datax  <- dnorm(x, mean=xbar, sd=se)
postx  <- dnorm(x, mean=Posterior[1], sd=Posterior[2])
plot(x, priorx, type='l',lwd=3,xlim = c(50,65),ylim=c(0,1),col = 'blue', main = '', xlab = 'theta', ylab = '')
lines(x, datax,col='black',lwd=3)
lines(x, postx,col='red',lwd=3)
legend("topright", c("Prior","Data","Posterior"), lty = 1, lwd= 3, col = c('blue','black','red'))
```
*Measures of spread*
```{r}
mysims <- rnorm(10000, mean = Posterior[1], sd = Posterior[2])
quantile(mysims, probs = c(0.25,0.75))
diff(quantile(mysims, probs = c(0.25,0.75)))
```


*Comparing Grades by Sex*
```{r}
studentdata %>% group_by(sex) %>% summarise(group.means = mean(G3), n = length(sex))

sigma = 50
se_male <- sigma/sqrt(n_male)
se_female <- sigma/sqrt(n_female)


```

```{r}
xbar1_F <- studentdata %>% filter(studentdata$sex == 'F') %>% 
  summarise(mean(G3)) %>% as.numeric()
xbar2_M <- studentdata %>% filter(studentdata$sex == 'M') %>% 
  summarise(mean(G3)) %>% as.numeric()
Prior <- c(m0, s0)
Grades_Female <- c(xbar1_F, se)
Grades_Male <- c(xbar2_M, se)
Posterior1_F <- normal_update(Prior, Grades_Female)
Posterior1_F

Posterior2_M <- normal_update(Prior, Grades_Male)
Posterior2_M

many_normal_plots(list(Prior,Posterior1_F,Posterior2_M)) + theme(legend.position = c(0.75,0.75))
```

